import * as fs from 'fs';
import * as path from 'path';
import { exec } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);

export interface DocumentationSet {
  readme: string;
  apiDocs: string;
  architectureDocs: string;
  changelog: string;
  setupGuide: string;
}

/**
 * The DocumentationGeneratorService is responsible for generating various types of documentation
 * for a project, including READMEs, API documentation, architecture overviews, changelogs,
 * and setup guides. It extracts information from `package.json`, analyzes code structure,
 * and can integrate with Git for commit history.
 */
export class DocumentationGeneratorService {
  private projectPath: string;

  constructor(projectPath: string) {
    this.projectPath = projectPath;
  }

  /**
   * Generates a comprehensive set of documentation or a specific type of document based on options.
   * @param options Optional parameters to specify the type of documentation to generate, a custom title, or specific sections for a report.
   * @returns A promise that resolves to the generated documentation content (string or object).
   */
  async generateDocumentation(options?: { type?: string; title?: string; sections?: string[] }): Promise<any> {
    if (options?.type) {
      switch (options.type) {
        case 'report':
          return this.generateProjectReport(options.title, options.sections);
        case 'technical':
          return this.generateArchitectureDocs();
        case 'changelog':
          return this.generateChangelog();
        default:
          return this.generateReadme();
      }
    }

    const [readme, apiDocs, architectureDocs, changelog, setupGuide] =
      await Promise.all([
        this.generateReadme(),
        this.generateAPIDocs(),
        this.generateArchitectureDocs(),
        this.generateChangelog(),
        this.generateSetupGuide(),
      ]);

    return {
      readme,
      apiDocs,
      architectureDocs,
      changelog,
      setupGuide,
    };
  }

  /**
   * Generates a README.md file for the project.
   * It extracts project name, description, and dependencies from `package.json`,
   * and includes sections for overview, features, getting started, project structure, API reference,
   * architecture, contributing guidelines, license, and support information.
   * @returns A promise that resolves to the Markdown content of the README.
   */
  private async generateReadme(): Promise<string> {
    const packageJsonPath = path.join(this.projectPath, 'package.json');
    const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf-8'));

    const readme = `# ${packageJson.name}

${packageJson.description || 'A project created with Synapse Browser'}

## Overview

This project was automatically analyzed and documented using Synapse Browser's AI documentation engine.

## Features

- Built with modern web technologies
- Fully typed with TypeScript
- Comprehensive test coverage
- Production-ready

## Getting Started

### Prerequisites

- Node.js 18 or higher
- npm or yarn

### Installation

\`\`\`bash
npm install
\`\`\`

### Development

\`\`\`bash
npm run dev
\`\`\`

The application will start on \`http://localhost:3000\`.

### Building

\`\`\`bash
npm run build
npm start
\`\`\`

### Testing

\`\`\`bash
npm test
\`\`\`

## Project Structure

\`\`\`
${this.generateDirectoryTree()}
\`\`\`

## Dependencies

### Production
\`\`\`json
${JSON.stringify(packageJson.dependencies || {}, null, 2)}
\`\`\`

### Development
\`\`\`json
${JSON.stringify(packageJson.devDependencies || {}, null, 2)}
\`\`\`

## API Reference

See [API Documentation](./docs/API.md) for detailed API endpoints and usage.

## Architecture

See [Architecture Guide](./docs/ARCHITECTURE.md) for system design and component overview.

## Contributing

1. Create a feature branch (\`git checkout -b feature/amazing-feature\`)
2. Commit your changes (\`git commit -m 'Add amazing feature'\`)
3. Push to the branch (\`git push origin feature/amazing-feature\`)
4. Open a Pull Request

## License

${packageJson.license || 'MIT'}

## Support

For issues and questions, please open an issue on GitHub.

---

*This README was auto-generated by Synapse Browser*
`;

    return readme;
  }

  /**
   * Generates a project analysis report with customizable title and sections.
   * This method provides a template for reports, indicating where analysis results would be inserted.
   * @param title Optional. The title of the project report. Defaults to 'Project Analysis Report'.
   * @param sections Optional. An array of section titles to include in the report. Defaults to ['Overview', 'Current Status', 'Key Metrics', 'Recommendations'].
   * @returns A promise that resolves to the Markdown content of the project report.
   */
  private async generateProjectReport(title?: string, sections?: string[]): Promise<string> {
    const reportTitle = title || 'Project Analysis Report';
    let report = `# ${reportTitle}\n\n`;
    
    const defaultSections = sections || ['Overview', 'Current Status', 'Key Metrics', 'Recommendations'];
    
    for (const section of defaultSections) {
      report += `## ${section}\n\n`;
      report += `Analysis for ${section} section of ${reportTitle} is being prepared based on the latest repository state.\n\n`;
    }
    
    return report;
  }

  /**
   * Generates API documentation by scanning for API routes within the project's `src/api` directory.
   * It extracts HTTP methods and paths to create a basic API reference.
   * @returns A promise that resolves to the Markdown content of the API documentation.
   */
  private async generateAPIDocs(): Promise<string> {
    let apiDocs = `# API Documentation

This document describes all available API endpoints.

## Base URL

\`\`\`
http://localhost:3000/api
\`\`\`

## Endpoints

`;

    // Scan for API routes
    const apiDir = path.join(this.projectPath, 'src', 'api');
    if (fs.existsSync(apiDir)) {
      const files = this.getAllFilesInDirectory(apiDir);

      for (const file of files) {
        const content = fs.readFileSync(file, 'utf-8');

        // Extract route definitions
        const routes = content.match(/router\.(get|post|put|delete|patch)\(['"]([^'"]+)['"]/g) || [];

        routes.forEach((route) => {
          const match = route.match(/router\.(get|post|put|delete|patch)\(['"]([^'"]+)['"]/);
          if (match) {
            const method = match[1].toUpperCase();
            const path = match[2];

            apiDocs += `\n### ${method} ${path}\n\n`;
            apiDocs += `**File:** \`${file}\`\n\n`;
            apiDocs += `**Method:** \`${method}\`\n\n`;
            apiDocs += `**Endpoint:** \`${path}\`\n\n`;
          }
        });
      }
    }

    if (apiDocs.trim() === '# API Documentation\n\nThis document describes all available API endpoints.\n\n## Base URL\n\n```\nhttp://localhost:3000/api\n```\n\n## Endpoints') {
      apiDocs += '\n\nNo API endpoints discovered in `src/api`.';
    }

    return apiDocs;
  }

  /**
   * Generates architecture documentation, providing an overview of the system's high-level design.
   * Includes sections for frontend, backend components, data flow, key modules, deployment architecture, security, and performance optimization.
   * @returns A promise that resolves to the Markdown content of the architecture documentation.
   */
  private async generateArchitectureDocs(): Promise<string> {
    const architectureDocs = `# Architecture Documentation

## System Overview

This document describes the high-level architecture of the application.

## Components

### Frontend

- **Framework:** React / Next.js
- **Styling:** Tailwind CSS
- **State Management:** [Add details]

### Backend

- **Runtime:** Node.js
- **Framework:** Express / Next.js API Routes
- **Database:** [Add details]

## Data Flow

\`\`\`
User Interface
    ↓
API Layer
    ↓
Business Logic
    ↓
Database
\`\`\`

## Key Modules

### Authentication
Handles user authentication and authorization.

### API Routes
RESTful API endpoints for data operations.

### Database Models
Data models and ORM definitions.

### Utilities
Helper functions and utilities.

## Deployment Architecture

\`\`\`
[Client] → [CDN] → [Load Balancer] → [App Servers] → [Database]
\`\`\`

## Security Considerations

- Environment variables for sensitive data
- HTTPS for all communications
- Input validation and sanitization
- CORS configuration
- Rate limiting

## Performance Optimization

- Code splitting and lazy loading
- Database query optimization
- Caching strategies
- Image optimization

---

*This architecture document was auto-generated by Synapse Browser*
`;

    return architectureDocs;
  }

  /**
   * Generates a changelog for the project, including recent commits from Git history if available.
   * It provides a structured overview of added, changed, and fixed features.
   * @returns A promise that resolves to the Markdown content of the changelog.
   */
  private async generateChangelog(): Promise<string> {
    let changelog = `# Changelog

All notable changes to this project will be documented in this file.

## [Unreleased]

### Added
- Initial project setup
- Core functionality

### Changed
- Project structure optimization

### Fixed
- Bug fixes and improvements

## [1.0.0] - ${new Date().toISOString().split('T')[0]}

### Added
- Initial release
- Project scaffolding
- Basic API endpoints
- Documentation

---

*This changelog was auto-generated by Synapse Browser*
`;

    // Try to extract recent commits
    try {
      const { stdout } = await execAsync('git log --oneline -20', {
        cwd: this.projectPath,
      });

      changelog += '\n## Recent Commits\n\n';
      changelog += stdout
        .split('\n')
        .filter((line) => line.trim())
        .map((line) => `- ${line}`)
        .join('\n');
    } catch (err) {
      // Git not available or not a git repo
    }

    return changelog;
  }

  /**
   * Generates a setup guide for the project, detailing prerequisites, installation steps, environment setup,
   * database configuration, development workflow, and troubleshooting tips.
   * @returns A promise that resolves to the Markdown content of the setup guide.
   */
  private async generateSetupGuide(): Promise<string> {
    const setupGuide = `# Setup Guide

## Prerequisites

- Node.js 18.0.0 or higher
- npm 9.0.0 or higher (or yarn 3.0.0+)
- Git

## Installation Steps

### 1. Clone the Repository

\`\`\`bash
git clone <repository-url>
cd <project-name>
\`\`\`

### 2. Install Dependencies

\`\`\`bash
npm install
\`\`\`

### 3. Environment Setup

Copy the example environment file and configure:

\`\`\`bash
cp .env.example .env.local
\`\`\`

Edit \`.env.local\` and add your configuration:

\`\`\`
DATABASE_URL=your_database_url
API_KEY=your_api_key
SECRET_KEY=your_secret_key
\`\`\`

### 4. Database Setup (if applicable)

\`\`\`bash
npm run db:setup
npm run db:migrate
\`\`\`

### 5. Start Development Server

\`\`\`bash
npm run dev
\`\`\`

Visit \`http://localhost:3000\` in your browser.

## Development Workflow

### Running Tests

\`\`\`bash
npm test
\`\`\`

### Building for Production

\`\`\`bash
npm run build
npm start
\`\`\`

### Code Quality

\`\`\`bash
npm run lint
npm run format
\`\`\`

## Troubleshooting

### Port Already in Use

If port 3000 is already in use, you can specify a different port:

\`\`\`bash
PORT=3001 npm run dev
\`\`\`

### Dependency Issues

Clear node_modules and reinstall:

\`\`\`bash
rm -rf node_modules
npm install
\`\`\`

### Database Connection Issues

Ensure your DATABASE_URL is correct and the database server is running.

## Next Steps

1. Read the [Architecture Documentation](./ARCHITECTURE.md)
2. Check the [API Documentation](./API.md)
3. Review the [Contributing Guidelines](./CONTRIBUTING.md)

---

*This setup guide was auto-generated by Synapse Browser*
`;

    return setupGuide;
  }

  /**
   * Generates a text-based directory tree of the project, excluding dotfiles and `node_modules`.
   * @returns A string representing the directory tree.
   */
  private generateDirectoryTree(): string {
    let tree = '';
    const dirs = fs.readdirSync(this.projectPath, { withFileTypes: true });

    dirs
      .filter((entry) => !entry.name.startsWith('.') && entry.name !== 'node_modules')
      .forEach((entry) => {
        if (entry.isDirectory()) {
          tree += `├── ${entry.name}/\n`;
        } else {
          tree += `├── ${entry.name}\n`;
        }
      });

    return tree;
  }

  /**
   * Recursively retrieves all file paths within a given directory.
   * @param dir The directory path to scan.
   * @returns An array of absolute file paths.
   */
  private getAllFilesInDirectory(dir: string): string[] {
    const files: string[] = [];

    const walk = (currentDir: string) => {
      const entries = fs.readdirSync(currentDir, { withFileTypes: true });
      entries.forEach((entry) => {
        const fullPath = path.join(currentDir, entry.name);

        if (entry.isDirectory()) {
          walk(fullPath);
        } else {
          files.push(fullPath);
        }
      });
    };

    walk(dir);
    return files;
  }

  /**
   * Saves the generated documentation to files within a 'docs' directory in the project path.
   * @param docs The `DocumentationSet` object containing all generated documentation content.
   * @returns A promise that resolves when all documentation files are saved.
   */
  async saveDocumentation(docs: DocumentationSet): Promise<void> {
    const docsDir = path.join(this.projectPath, 'docs');

    if (!fs.existsSync(docsDir)) {
      fs.mkdirSync(docsDir, { recursive: true });
    }

    fs.writeFileSync(path.join(this.projectPath, 'README.md'), docs.readme);
    fs.writeFileSync(path.join(docsDir, 'API.md'), docs.apiDocs);
    fs.writeFileSync(path.join(docsDir, 'ARCHITECTURE.md'), docs.architectureDocs);
    fs.writeFileSync(path.join(docsDir, 'CHANGELOG.md'), docs.changelog);
    fs.writeFileSync(path.join(docsDir, 'SETUP.md'), docs.setupGuide);
  }
}
