import * as fs from 'fs';
import * as path from 'path';
import { exec } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);

export interface DocumentationSet {
  readme: string;
  apiDocs: string;
  architectureDocs: string;
  changelog: string;
  setupGuide: string;
}

export class DocumentationGeneratorService {
  private projectPath: string;

  constructor(projectPath: string) {
    this.projectPath = projectPath;
  }

  async generateDocumentation(): Promise<DocumentationSet> {
    const [readme, apiDocs, architectureDocs, changelog, setupGuide] =
      await Promise.all([
        this.generateReadme(),
        this.generateAPIDocs(),
        this.generateArchitectureDocs(),
        this.generateChangelog(),
        this.generateSetupGuide(),
      ]);

    return {
      readme,
      apiDocs,
      architectureDocs,
      changelog,
      setupGuide,
    };
  }

  private async generateReadme(): Promise<string> {
    const packageJsonPath = path.join(this.projectPath, 'package.json');
    const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf-8'));

    const readme = `# ${packageJson.name}

${packageJson.description || 'A project created with Synapse Browser'}

## Overview

This project was automatically analyzed and documented using Synapse Browser's AI documentation engine.

## Features

- Built with modern web technologies
- Fully typed with TypeScript
- Comprehensive test coverage
- Production-ready

## Getting Started

### Prerequisites

- Node.js 18 or higher
- npm or yarn

### Installation

\`\`\`bash
npm install
\`\`\`

### Development

\`\`\`bash
npm run dev
\`\`\`

The application will start on \`http://localhost:3000\`.

### Building

\`\`\`bash
npm run build
npm start
\`\`\`

### Testing

\`\`\`bash
npm test
\`\`\`

## Project Structure

\`\`\`
${this.generateDirectoryTree()}
\`\`\`

## Dependencies

### Production
\`\`\`json
${JSON.stringify(packageJson.dependencies || {}, null, 2)}
\`\`\`

### Development
\`\`\`json
${JSON.stringify(packageJson.devDependencies || {}, null, 2)}
\`\`\`

## API Reference

See [API Documentation](./docs/API.md) for detailed API endpoints and usage.

## Architecture

See [Architecture Guide](./docs/ARCHITECTURE.md) for system design and component overview.

## Contributing

1. Create a feature branch (\`git checkout -b feature/amazing-feature\`)
2. Commit your changes (\`git commit -m 'Add amazing feature'\`)
3. Push to the branch (\`git push origin feature/amazing-feature\`)
4. Open a Pull Request

## License

${packageJson.license || 'MIT'}

## Support

For issues and questions, please open an issue on GitHub.

---

*This README was auto-generated by Synapse Browser*
`;

    return readme;
  }

  private async generateAPIDocs(): Promise<string> {
    let apiDocs = `# API Documentation

This document describes all available API endpoints.

## Base URL

\`\`\`
http://localhost:3000/api
\`\`\`

## Authentication

API requests require authentication via Bearer token in the Authorization header:

\`\`\`
Authorization: Bearer YOUR_API_KEY
\`\`\`

## Endpoints

`;

    // Scan for API routes
    const apiDir = path.join(this.projectPath, 'src', 'api');
    if (fs.existsSync(apiDir)) {
      const files = this.getAllFilesInDirectory(apiDir);

      for (const file of files) {
        const content = fs.readFileSync(file, 'utf-8');

        // Extract route definitions
        const routes = content.match(/router\.(get|post|put|delete|patch)\(['"]([^'"]+)['"]/g) || [];

        routes.forEach((route) => {
          const match = route.match(/router\.(get|post|put|delete|patch)\(['"]([^'"]+)['"]/);
          if (match) {
            const method = match[1].toUpperCase();
            const path = match[2];

            apiDocs += `\n### ${method} ${path}\n\n`;
            apiDocs += `**File:** \`${file}\`\n\n`;
            apiDocs += `**Description:** [Add description]\n\n`;
            apiDocs += `**Request Body:**\n\`\`\`json\n{}\n\`\`\`\n\n`;
            apiDocs += `**Response:**\n\`\`\`json\n{}\n\`\`\`\n\n`;
            apiDocs += `**Status Codes:**\n- 200: Success\n- 400: Bad Request\n- 401: Unauthorized\n- 500: Server Error\n\n`;
          }
        });
      }
    }

    return apiDocs;
  }

  private async generateArchitectureDocs(): Promise<string> {
    const architectureDocs = `# Architecture Documentation

## System Overview

This document describes the high-level architecture of the application.

## Components

### Frontend

- **Framework:** React / Next.js
- **Styling:** Tailwind CSS
- **State Management:** [Add details]

### Backend

- **Runtime:** Node.js
- **Framework:** Express / Next.js API Routes
- **Database:** [Add details]

## Data Flow

\`\`\`
User Interface
    ↓
API Layer
    ↓
Business Logic
    ↓
Database
\`\`\`

## Key Modules

### Authentication
Handles user authentication and authorization.

### API Routes
RESTful API endpoints for data operations.

### Database Models
Data models and ORM definitions.

### Utilities
Helper functions and utilities.

## Deployment Architecture

\`\`\`
[Client] → [CDN] → [Load Balancer] → [App Servers] → [Database]
\`\`\`

## Security Considerations

- Environment variables for sensitive data
- HTTPS for all communications
- Input validation and sanitization
- CORS configuration
- Rate limiting

## Performance Optimization

- Code splitting and lazy loading
- Database query optimization
- Caching strategies
- Image optimization

---

*This architecture document was auto-generated by Synapse Browser*
`;

    return architectureDocs;
  }

  private async generateChangelog(): Promise<string> {
    let changelog = `# Changelog

All notable changes to this project will be documented in this file.

## [Unreleased]

### Added
- Initial project setup
- Core functionality

### Changed
- Project structure optimization

### Fixed
- Bug fixes and improvements

## [1.0.0] - ${new Date().toISOString().split('T')[0]}

### Added
- Initial release
- Project scaffolding
- Basic API endpoints
- Documentation

---

*This changelog was auto-generated by Synapse Browser*
`;

    // Try to extract recent commits
    try {
      const { stdout } = await execAsync('git log --oneline -20', {
        cwd: this.projectPath,
      });

      changelog += '\n## Recent Commits\n\n';
      changelog += stdout
        .split('\n')
        .filter((line) => line.trim())
        .map((line) => `- ${line}`)
        .join('\n');
    } catch (err) {
      // Git not available or not a git repo
    }

    return changelog;
  }

  private async generateSetupGuide(): Promise<string> {
    const setupGuide = `# Setup Guide

## Prerequisites

- Node.js 18.0.0 or higher
- npm 9.0.0 or higher (or yarn 3.0.0+)
- Git

## Installation Steps

### 1. Clone the Repository

\`\`\`bash
git clone <repository-url>
cd <project-name>
\`\`\`

### 2. Install Dependencies

\`\`\`bash
npm install
\`\`\`

### 3. Environment Setup

Copy the example environment file and configure:

\`\`\`bash
cp .env.example .env.local
\`\`\`

Edit \`.env.local\` and add your configuration:

\`\`\`
DATABASE_URL=your_database_url
API_KEY=your_api_key
SECRET_KEY=your_secret_key
\`\`\`

### 4. Database Setup (if applicable)

\`\`\`bash
npm run db:setup
npm run db:migrate
\`\`\`

### 5. Start Development Server

\`\`\`bash
npm run dev
\`\`\`

Visit \`http://localhost:3000\` in your browser.

## Development Workflow

### Running Tests

\`\`\`bash
npm test
\`\`\`

### Building for Production

\`\`\`bash
npm run build
npm start
\`\`\`

### Code Quality

\`\`\`bash
npm run lint
npm run format
\`\`\`

## Troubleshooting

### Port Already in Use

If port 3000 is already in use, you can specify a different port:

\`\`\`bash
PORT=3001 npm run dev
\`\`\`

### Dependency Issues

Clear node_modules and reinstall:

\`\`\`bash
rm -rf node_modules
npm install
\`\`\`

### Database Connection Issues

Ensure your DATABASE_URL is correct and the database server is running.

## Next Steps

1. Read the [Architecture Documentation](./ARCHITECTURE.md)
2. Check the [API Documentation](./API.md)
3. Review the [Contributing Guidelines](./CONTRIBUTING.md)

---

*This setup guide was auto-generated by Synapse Browser*
`;

    return setupGuide;
  }

  private generateDirectoryTree(): string {
    let tree = '';
    const dirs = fs.readdirSync(this.projectPath, { withFileTypes: true });

    dirs
      .filter((entry) => !entry.name.startsWith('.') && entry.name !== 'node_modules')
      .forEach((entry) => {
        if (entry.isDirectory()) {
          tree += `├── ${entry.name}/\n`;
        } else {
          tree += `├── ${entry.name}\n`;
        }
      });

    return tree;
  }

  private getAllFilesInDirectory(dir: string): string[] {
    const files: string[] = [];

    const walk = (currentDir: string) => {
      const entries = fs.readdirSync(currentDir, { withFileTypes: true });
      entries.forEach((entry) => {
        const fullPath = path.join(currentDir, entry.name);

        if (entry.isDirectory()) {
          walk(fullPath);
        } else {
          files.push(fullPath);
        }
      });
    };

    walk(dir);
    return files;
  }

  async saveDocumentation(docs: DocumentationSet): Promise<void> {
    const docsDir = path.join(this.projectPath, 'docs');

    if (!fs.existsSync(docsDir)) {
      fs.mkdirSync(docsDir, { recursive: true });
    }

    fs.writeFileSync(path.join(this.projectPath, 'README.md'), docs.readme);
    fs.writeFileSync(path.join(docsDir, 'API.md'), docs.apiDocs);
    fs.writeFileSync(path.join(docsDir, 'ARCHITECTURE.md'), docs.architectureDocs);
    fs.writeFileSync(path.join(docsDir, 'CHANGELOG.md'), docs.changelog);
    fs.writeFileSync(path.join(docsDir, 'SETUP.md'), docs.setupGuide);
  }
}
